version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "updating git ..."; apt-get update; apt-get install -y python-software-properties software-properties-common; add-apt-repository ppa:git-core/ppa; apt-get update; apt-get install -y git
      - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - echo "machine github.com login ${GH_USERNAME} password ${GH_TOKEN}" > ~/.netrc
      - npm install -g npm@
      - export GK_LOCK_DEFAULT_BRANCH=v1
      - npm i -g greenkeeper-lockfile@2
      - npx greenkeeper-lockfile-update
      - npm ci --no-audit
  build:
    commands:
      - npm run test
      - npx greenkeeper-lockfile-upload
