name: Unit Test

on:
    push:
        branches: [ v1 ]
    pull_request:
        branches: [ v1 ]

jobs:
    unit-tests:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
            - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
              with:
                  node-version: 16
            - name: Install Dependencies
              run: npm install
            - name: Run Tests
              run: npm test
